version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sdsu_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sdsu
      POSTGRES_PASSWORD: sdsu
      POSTGRES_DB: sdsu_search
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
